# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Electro Shoxx
email: shoxx@shoxxdj.fr
description: "A series of electro podcasts"
subtitle: "Retro, classical, actual"
lang: en-us
author: shoxxdj
copyright: "CC-BY 4.0"
baseurl: "/dj-podcasts" # the subpath of your site, e.g. /blog
url: "https://shoxxdj.github.io" # the base hostname & protocol for your site
twitter_username: shoxxdj
github_username:  shoxxdj

permalink: /:year/:title.html

#Timezone
timezone: Europa/Paris

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

theme: jekyll-theme-minimal
